channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - seaborn
  - scipy
  - pip
  - pip:
    - nbgitpuller
    - pandas
    - matplotlib
    - nilearn
    - osfclient
    - "https://github.com/wichmann-lab/python-psignifit/zipball/master"
