channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - seaborn
  - scipy
  - pandas
  - matplotlib
  - nbgitpuller
  - pip
  - pip:
    - nilearn
    - osfclient
    - psignifit
