channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - seaborn
  - scipy
  - pandas
  - matplotlib
  - nbgitpuller
  - pip
  - pip:
    - nilearn
    - osfclient
    - "https://github.com/wichmann-lab/python-psignifit/zipball/master"
